# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

#[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
[colors.normal]
black   = '#1b1d2b'
red     = '#ff757f'
green   = '#9ece6a'
yellow  = '#ffc777'
blue    = '#7aa2f7'
magenta = '#c099ff'
cyan    = '#449dab'
white   = '#b8c0e0'

# Bright colors
[colors.bright]
black   = '#444a73'
red     = '#ff757f'
green   = '#c3e88d'
yellow  = '#ffdb69'
blue    = '#82aaff'
magenta = '#c099ff'
cyan    = '#86e1fc'
white   = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'
