k9s:
  cluster: default
  namespace:
    active: default
    lockFavorites: true
    favorites:
    - default
    - database
    - downloads
    - grenadianbuzz
    - flux-system
    - kube-system
    - media
    - monitoring
    - system-upgrade
  view:
    active: xray deploy
  featureGates:
    nodeShell: true
  portForwardAddress: localhost
