k9s:
  cluster: default
  namespace:
    active: default
    lockFavorites: true
    favorites:
      - default
      - database
      - grenadianbuzz
      - kube-system
      - media
      - flux-system
      - download
  view:
    active: deploy
  featureGates:
    nodeShell: true
  portForwardAddress: localhost
